import {apiFetch} from '@/lib/api/client';
type R<T>={success:boolean;data:T};
export type LifecycleRecord={id:string;organization_id:string;organization_name:string;industry:string|null;stage:string;priority:string;pursuit_progress:number;assigned_to_id:string|null;owner_first_name:string|null;owner_last_name:string|null;contact_count:number;open_tasks:number;expected_revenue:number|null;actual_revenue:number|null;client_revenue_recorded_at:string|null;converted_to_prospect_at:string|null;converted_to_client_at:string|null;updated_at:string};
export type DashboardData={kpi:{total_leads:number;active_pursuits:number;prospects:number;clients:number;overdue_tasks:number;followups_today:number;ready_for_review:number};stages:Array<{stage:string;count:number}>;staff:Array<{id:string;first_name:string;last_name:string;assigned_tasks:number;completed_tasks:number;overdue_tasks:number;assigned_leads:number}>;recent:Array<{id:string;action:string;module:string|null;entity_type:string|null;entity_id:string|null;created_at:string;first_name:string|null;last_name:string|null}>;upcoming:Array<{id:string;title:string;activity_type:string;scheduled_at:string;lead_id:string|null;organization_id:string|null;organization_name:string|null;assignee_first_name:string|null;assignee_last_name:string|null}>};
export type CalendarData={activities:Array<{id:string;title:string;activity_type:string;status:string;scheduled_at:string;organization_name:string|null;assignee_first_name:string|null;assignee_last_name:string|null}>;tasks:Array<{id:string;title:string;status:string;priority:string;due_at:string;organization_name:string|null;assignee_first_name:string|null;assignee_last_name:string|null}>};
export type StaffHome={summary:{open_tasks:number;overdue_tasks:number;assigned_leads:number;followups_today:number};tasks:Array<{id:string;title:string;status:string;priority:string;due_at:string|null}>;leads:Array<{id:string;stage:string;priority:string;pursuit_progress:number;organization_name:string}>;followups:Array<{id:string;title:string;activity_type:string;scheduled_at:string;organization_name:string|null}>};
export async function getDashboard(){return(await apiFetch<R<DashboardData>>('/admin/dashboard')).data}
export async function listLifecycle(type:'PROSPECT'|'CLIENT'){return(await apiFetch<R<LifecycleRecord[]>>(type==='PROSPECT'?'/admin/prospects':'/admin/clients')).data}
export async function approveProspect(id:string){return(await apiFetch<R<unknown>>(`/admin/leads/${id}/approve-prospect`,{method:'POST'})).data}
export async function rejectProspect(id:string,reason?:string){return(await apiFetch<R<unknown>>(`/admin/leads/${id}/reject-prospect`,{method:'POST',body:JSON.stringify({reason})})).data}
export async function convertClient(id:string){return(await apiFetch<R<unknown>>(`/admin/prospects/${id}/convert-client`,{method:'POST'})).data}
export async function recordClientRevenue(id:string,amount:number){return(await apiFetch<R<unknown>>(`/admin/clients/${id}/revenue`,{method:'POST',body:JSON.stringify({amount})})).data}
export async function getCalendar(staff:boolean){return(await apiFetch<R<CalendarData>>(staff?'/staff/calendar':'/admin/calendar')).data}
export async function getStaffHome(){return(await apiFetch<R<StaffHome>>('/staff/home-summary')).data}
export async function taskAccept(id:string){return(await apiFetch<R<unknown>>(`/staff/tasks/${id}/accept`,{method:'POST'})).data}
export async function taskStart(id:string){return(await apiFetch<R<unknown>>(`/staff/tasks/${id}/start`,{method:'POST'})).data}
export async function taskSubmit(id:string){return(await apiFetch<R<unknown>>(`/staff/tasks/${id}/submit`,{method:'POST'})).data}
export async function reviewTask(id:string,decision:'APPROVE'|'REVISION',message?:string){return(await apiFetch<R<unknown>>(`/admin/tasks/${id}/review`,{method:'POST',body:JSON.stringify({decision,message})})).data}
export type AuditItem={id:string;action:string;module:string;entity_type:string;entity_id:string|null;old_values:unknown|null;new_values:unknown|null;created_at:string;ip_address:string|null;user_agent:string|null;actor_user_id:string|null;actor_first_name:string|null;actor_last_name:string|null;actor_email:string|null;actor_role_code:string|null;actor_role_name:string|null;actor_department_name:string|null;actor_user_id_snapshot:string|null;actor_name_snapshot:string|null;actor_email_snapshot:string|null;actor_role_snapshot:string|null;actor_department_snapshot:string|null};
export type AuditPage={items:AuditItem[];total:number;limit:number;offset:number};
export async function getAuditFeed(limit=250,offset=0){return(await apiFetch<R<AuditPage>>(`/admin/audit-feed?limit=${limit}&offset=${offset}`)).data}
export type LatestActivityItem={id:string;action:string;module:string;entity_type:string;entity_id:string|null;created_at:string;actor_user_id:string|null;actor_first_name:string|null;actor_last_name:string|null;actor_email:string|null;actor_role_name:string|null;actor_department_name:string|null;entity_title:string|null;record_type:'LEAD'|'PROSPECT'|'CLIENT'|null;lead_stage:string|null;href:string|null};
export async function getLatestActivities(){return(await apiFetch<R<LatestActivityItem[]>>('/admin/latest-activities')).data}
