'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {AppShell} from '@/components/shell/app-shell';
import {Button} from '@/components/ui/button';
import {Card} from '@/components/ui/card';
import {getCompanyReport,type CompanyReport,type CompanyReportFilters} from '@/lib/workspace/api';

const empty:CompanyReportFilters={focus:'overview'};
export function ReportsView(){
 const[filters,setFilters]=useState<CompanyReportFilters>(empty),[data,setData]=useState<CompanyReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const load=useCallback(async(next=filters)=>{setLoading(true);setError(null);try{setData(await getCompanyReport(next))}catch(e){setError(e instanceof Error?e.message:'Unable to load reports.');}finally{setLoading(false)}},[filters]);
 useEffect(()=>{let cancelled=false;void Promise.resolve().then(async()=>{try{const report=await getCompanyReport(empty);if(!cancelled)setData(report)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Unable to load reports.')}finally{if(!cancelled)setLoading(false)}});return()=>{cancelled=true}},[]);
 const lifecycle=useMemo(()=>Object.fromEntries((data?.lifecycle??[]).map(r=>[r.record_type,Number(r.count)])),[data]);
 const set=(k:keyof CompanyReportFilters,v:string)=>setFilters(x=>({...x,[k]:v||undefined}));
 return <AppShell area="admin" title="Reports" breadcrumb="Insights" description="Filter management reports by staff, department, company, Lead lifecycle and task delivery." actions={<Button variant="outline" disabled={!data} onClick={()=>data&&downloadCsv(data)}>Export filtered CSV</Button>}>
  <div className="report-page">
   <Card className="report-filter-card report-filter-card-pro">
    <div className="report-filter-heading"><span className="eyebrow">Report builder</span><h2>Filtered management report</h2><p>Use one or several filters. Clear them to return to the company-wide view.</p></div>
    <label><span>Focus</span><select value={filters.focus??'overview'} onChange={e=>set('focus',e.target.value)}><option value="overview">Company overview</option><option value="staff">Staff performance</option><option value="leads">Leads & pipeline</option><option value="organizations">Companies / organizations</option><option value="tasks">Tasks & delivery</option><option value="followups">Follow-ups</option></select></label>
    <label><span>Staff</span><select value={filters.staffId??''} onChange={e=>set('staffId',e.target.value)}><option value="">All staff</option>{data?.options.staff.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></label>
    <label><span>Department</span><select value={filters.departmentId??''} onChange={e=>set('departmentId',e.target.value)}><option value="">All departments</option>{data?.options.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
    <label><span>Company</span><select value={filters.organizationId??''} onChange={e=>set('organizationId',e.target.value)}><option value="">All companies</option>{data?.options.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
    <label><span>CRM record</span><select value={filters.recordType??''} onChange={e=>set('recordType',e.target.value)}><option value="">All lifecycle records</option><option value="LEAD">Leads</option><option value="PROSPECT">Prospects</option><option value="CLIENT">Clients</option></select></label>
    <label><span>Lead stage</span><select value={filters.leadStage??''} onChange={e=>set('leadStage',e.target.value)}><option value="">All stages</option>{data?.options.leadStages.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select></label>
    <label><span>Task status</span><select value={filters.taskStatus??''} onChange={e=>set('taskStatus',e.target.value)}><option value="">All task statuses</option>{data?.options.taskStatuses.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select></label>
    <label><span>From</span><input type="date" value={filters.from??''} onChange={e=>set('from',e.target.value)}/></label>
    <label><span>To</span><input type="date" value={filters.to??''} onChange={e=>set('to',e.target.value)}/></label>
    <div className="report-filter-actions"><Button onClick={()=>void load(filters)} loading={loading}>Apply filters</Button><Button variant="outline" onClick={()=>{setFilters(empty);void load(empty)}}>Clear</Button></div>
   </Card>
   {error?<Card className="report-error-state"><strong>Reports could not be loaded</strong><p>{error}</p><Button onClick={()=>void load(filters)}>Try again</Button></Card>:null}
   {loading&&!data?<Card className="workspace-card"><p className="muted">Loading report…</p></Card>:null}
   {data&&!error?<>
    <div className="report-kpi-grid"><Metric label="Leads" value={lifecycle.LEAD??0}/><Metric label="Prospects" value={lifecycle.PROSPECT??0}/><Metric label="Clients" value={lifecycle.CLIENT??0}/><Metric label="Overdue follow-ups" value={Number(data.followUps.overdue??0)} tone="danger"/></div>
    <div className="report-grid"><Card className="workspace-card"><header><div><span className="eyebrow">Sales lifecycle</span><h2>Lead stages</h2></div></header><Bars rows={data.leadStages.map(x=>({label:pretty(x.stage),value:Number(x.count)}))}/></Card><Card className="workspace-card"><header><div><span className="eyebrow">Delivery</span><h2>Task status</h2></div></header><Bars rows={data.tasks.map(x=>({label:pretty(x.status),value:Number(x.count)}))}/></Card></div>
    {(filters.focus==='overview'||filters.focus==='staff'||!filters.focus)?<Card className="workspace-card"><header><div><span className="eyebrow">Team performance</span><h2>Staff delivery</h2><p>Filter a staff member or department above for an individual performance report.</p></div></header><div className="report-table-wrap"><table className="report-table"><thead><tr><th>Staff</th><th>Department</th><th>Role</th><th>Assigned</th><th>Completed</th><th>Overdue</th><th>Active leads</th><th>Delivery rate</th></tr></thead><tbody>{data.staff.map(s=>{const assigned=Number(s.assigned_tasks),done=Number(s.completed_tasks);return <tr key={s.id}><td><strong>{s.first_name} {s.last_name}</strong></td><td>{s.department_name||'—'}</td><td>{s.job_title||'Staff'}</td><td>{assigned}</td><td>{done}</td><td className={Number(s.overdue_tasks)>0?'overdue-text':''}>{Number(s.overdue_tasks)}</td><td>{Number(s.active_leads)}</td><td>{assigned?Math.round(done/assigned*100):0}%</td></tr>})}</tbody></table></div></Card>:null}
    {(filters.focus==='overview'||filters.focus==='organizations')?<Card className="workspace-card"><header><div><span className="eyebrow">Company view</span><h2>Organization activity</h2><p>CRM records, contacts and delivery activity by company.</p></div></header><div className="report-table-wrap"><table className="report-table"><thead><tr><th>Company</th><th>Industry</th><th>CRM records</th><th>Contacts</th><th>Tasks</th><th>Overdue tasks</th></tr></thead><tbody>{data.organizations.map(o=><tr key={o.id}><td><strong>{o.name}</strong></td><td>{o.industry||'—'}</td><td>{o.crm_records}</td><td>{o.contacts}</td><td>{o.tasks}</td><td className={Number(o.overdue_tasks)>0?'overdue-text':''}>{o.overdue_tasks}</td></tr>)}</tbody></table></div></Card>:null}
   </>:null}
  </div>
 </AppShell>
}
function Metric({label,value,tone}:{label:string;value:number;tone?:'danger'}){return <Card className={`report-metric ${tone?'is-danger':''}`}><span>{label}</span><strong>{value}</strong></Card>}
function Bars({rows}:{rows:Array<{label:string;value:number}>}){const max=Math.max(1,...rows.map(r=>r.value));return <div className="report-bars">{rows.length?rows.map(r=><div className="report-bar-row" key={r.label}><div><span>{r.label}</span><strong>{r.value}</strong></div><div className="report-bar-track"><span style={{width:`${Math.max(3,r.value/max*100)}%`}}/></div></div>):<p className="muted">No data for this filter.</p>}</div>}
function pretty(v:string){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())}
function downloadCsv(data:CompanyReport){const rows=[['PlanoraHub Filtered Management Report'],['From',data.range.from??'All time','To',data.range.to??'Current'],[],['Lifecycle','Count'],...data.lifecycle.map(x=>[x.record_type,String(x.count)]),[],['Staff','Department','Role','Assigned Tasks','Completed Tasks','Overdue Tasks','Active Leads'],...data.staff.map(s=>[`${s.first_name} ${s.last_name}`,s.department_name??'',s.job_title??'',String(s.assigned_tasks),String(s.completed_tasks),String(s.overdue_tasks),String(s.active_leads)]),[],['Company','Industry','CRM Records','Contacts','Tasks','Overdue Tasks'],...data.organizations.map(o=>[o.name,o.industry??'',String(o.crm_records),String(o.contacts),String(o.tasks),String(o.overdue_tasks)])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='PlanoraHub-filtered-report.csv';a.click();URL.revokeObjectURL(url)}
