'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { EmptyState } from '@/components/ui/empty-state';
import { Icon } from '@/components/ui/icon';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { PageErrorState, PageLoadingState } from '@/components/ui/page-state';
import { listTasks } from '@/lib/leads/api';
import type { TaskDetail } from '@/lib/leads/types';
import { listTeamActivity, setTeamActivityReviewed, type TeamActivityData, type TeamActivityItem } from '@/lib/team-activity/api';

export const teamActivityLabels: Record<string, string> = {
  ACTIVITY_CREATED: 'Activity logged', FOLLOW_UP_SCHEDULED: 'Follow-up scheduled', FOLLOW_UP_COMPLETED: 'Follow-up completed', FOLLOW_UP_CANCELLED: 'Follow-up cancelled', FOLLOW_UP_RESCHEDULED: 'Follow-up rescheduled', TASK_CREATED: 'Task created', TASK_WORKFLOW_UPDATED: 'Task updated', TASK_ACCEPTED: 'Task accepted', TASK_STARTED: 'Task started', TASK_ATTACHMENT_UPLOADED: 'Task file uploaded', TASK_SUBMITTED_FOR_REVIEW: 'Task submitted for review', TASK_APPROVED: 'Task approved', TASK_REVISION_REQUESTED: 'Task revision requested', LEAD_ASSIGNED: 'Lead assigned', LEAD_REASSIGNED: 'Lead reassigned', LEAD_ASSIGNMENT_BATCH_CREATED: 'Lead batch assigned', LEAD_PURSUIT_STEP_COMPLETED: 'Pursuit step completed', LEAD_PURSUIT_EVIDENCE_UPLOADED: 'Pursuit evidence uploaded', LEAD_PURSUIT_STAFF_STEP_ADDED: 'Staff pursuit step added', LEAD_PURSUIT_ADMIN_STEP_ADDED: 'Required pursuit step added', LEAD_PURSUIT_RETAKE_REQUESTED: 'Pursuit retake requested', LEAD_PURSUIT_COMMENT_ADDED: 'Pursuit feedback added',
};

type Period = 'ALL' | 'TODAY' | '7D' | '30D' | 'CUSTOM';
type WorkView = 'REVIEWED' | 'UNREVIEWED' | 'OVERDUE';

function localDate(offsetDays = 0) { const date = new Date(); date.setDate(date.getDate() + offsetDays); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
export function teamActivityActor(item: TeamActivityItem) { return [item.actor_first_name, item.actor_last_name].filter(Boolean).join(' ') || item.actor_email || 'System'; }
export function teamActivityDetail(item: TeamActivityItem) { const value=item.new_values??{}; if(item.action==='LEAD_PURSUIT_STEP_COMPLETED')return typeof value.title==='string'?`Completed ${value.title}`:'Completed a pursuit step'; if(item.action==='LEAD_PURSUIT_EVIDENCE_UPLOADED')return typeof value.fileName==='string'?`Uploaded ${value.fileName}`:'Uploaded pursuit evidence'; if(item.action==='LEAD_REASSIGNED')return 'Changed Lead ownership'; if(item.action==='LEAD_ASSIGNMENT_BATCH_CREATED')return typeof value.title==='string'?value.title:'Created a Lead assignment batch'; if(item.action==='TASK_WORKFLOW_UPDATED'){const oldStatus=typeof item.old_values?.status==='string'?item.old_values.status:null;const newStatus=typeof item.new_values?.status==='string'?item.new_values.status:null;if(oldStatus!=='COMPLETED'&&newStatus==='COMPLETED')return `Completed ${item.task_title??'task'}`;if(oldStatus==='COMPLETED'&&newStatus!=='COMPLETED')return `Reopened ${item.task_title??'task'}`;} return item.task_title??item.activity_title??item.lead_title??teamActivityLabels[item.action]??item.action.replaceAll('_',' ').toLowerCase(); }
export function teamActivityDateTime(value:string){return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));}

export function TeamActivityView() {
  const [data,setData]=useState<TeamActivityData|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
  const [search,setSearch]=useState(''),[debouncedSearch,setDebouncedSearch]=useState(''),[staffId,setStaffId]=useState(''),[type,setType]=useState(''),[leadId,setLeadId]=useState(''),[organizationId,setOrganizationId]=useState(''),[reviewed,setReviewed]=useState('false');
  const [period,setPeriod]=useState<Period>('ALL'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[updatingId,setUpdatingId]=useState<string|null>(null),[overdueTasks,setOverdueTasks]=useState<TaskDetail[]>([]),[workView,setWorkView]=useState<WorkView>('UNREVIEWED');

  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedSearch(search),180);return()=>window.clearTimeout(timer)},[search]);
  useEffect(()=>{let active=true;listTasks(false).then(tasks=>{if(!active)return;const now=Date.now();setOverdueTasks(tasks.filter(task=>task.status!=='COMPLETED'&&task.status!=='CANCELLED'&&Boolean(task.due_at)&&new Date(task.due_at as string).getTime()<now))}).catch(()=>undefined);return()=>{active=false}},[]);

  const effectiveDates=useMemo(()=>{if(period==='TODAY')return{from:localDate(),to:localDate()};if(period==='7D')return{from:localDate(-6),to:localDate()};if(period==='30D')return{from:localDate(-29),to:localDate()};if(period==='CUSTOM')return{from,to};return{from:'',to:''}},[period,from,to]);
  const query=useMemo(()=>({search:debouncedSearch,staffId,type,leadId,organizationId,reviewed,from:effectiveDates.from,to:effectiveDates.to}),[debouncedSearch,staffId,type,leadId,organizationId,reviewed,effectiveDates.from,effectiveDates.to]);
  const refresh=useCallback(async()=>{setRefreshing(true);try{const value=await listTeamActivity(query);setData(value);setError(null);return value}catch(caught){setError(caught instanceof Error?caught.message:'Unable to load team activity.');return null}finally{setRefreshing(false)}},[query]);
  useEffect(()=>{let cancelled=false;listTeamActivity(query).then(value=>{if(!cancelled){setData(value);setError(null)}}).catch((caught:unknown)=>{if(!cancelled)setError(caught instanceof Error?caught.message:'Unable to load team activity.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[query]);
  if(loading&&!data)return <PageLoadingState/>; if(error&&!data)return <PageErrorState message={error}/>;

  const items=data?.items??[];
  async function toggleReviewed(item:TeamActivityItem){setUpdatingId(item.id);setData(current=>current?{...current,items:current.items.map(entry=>entry.id===item.id?{...entry,reviewed:!item.reviewed}:entry)}:current);try{await setTeamActivityReviewed(item.id,!item.reviewed);await refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Unable to update review status.');await refresh()}finally{setUpdatingId(null)}}
  const periodOptions:Array<[Period,string]>=[['ALL','All'],['TODAY','Today'],['7D','7 days'],['30D','30 days'],['CUSTOM','Custom']];
  const changeWorkView=(next:WorkView)=>{setWorkView(next);setReviewed(next==='REVIEWED'?'true':next==='UNREVIEWED'?'false':'')};

  return <div className="team-activity-page">
    <Card className="team-activity-controls"><div className="team-activity-control-row">
      <div className="team-activity-control-group"><span className="team-activity-label">Period</span><div className="team-activity-segment">{periodOptions.map(([value,label])=><Button key={value} type="button" size="sm" variant={period===value?'secondary':'ghost'} onClick={()=>setPeriod(value)}>{label}</Button>)}</div></div>
      <div className="team-activity-control-group"><span className="team-activity-label">Review status</span><div className="team-activity-segment">{([['UNREVIEWED','Unreviewed'],['REVIEWED','Reviewed'],['OVERDUE',`Overdue (${overdueTasks.length})`]] as const).map(([value,label])=><Button key={value} type="button" size="sm" variant={workView===value?'secondary':'ghost'} onClick={()=>changeWorkView(value)}>{label}</Button>)}</div></div>
    </div><div className="team-activity-filter-grid"><Input label="Search" placeholder="Staff, action, notes…" value={search} onChange={event=>setSearch(event.target.value)}/><NativeSelect label="Staff" value={staffId} onChange={event=>setStaffId(event.target.value)}><option value="">All staff</option>{(data?.staff??[]).map(person=><option key={person.id} value={person.id}>{person.first_name} {person.last_name}</option>)}</NativeSelect><NativeSelect label="Type" value={type} onChange={event=>setType(event.target.value)}><option value="">All activity types</option>{(data?.types??[]).map(value=><option key={value} value={value}>{teamActivityLabels[value]??value}</option>)}</NativeSelect><NativeSelect label="Lead" value={leadId} onChange={event=>setLeadId(event.target.value)}><option value="">All Leads</option>{(data?.leads??[]).map(lead=><option key={lead.id} value={lead.id}>{lead.title}</option>)}</NativeSelect><NativeSelect label="Organization" value={organizationId} onChange={event=>setOrganizationId(event.target.value)}><option value="">All organizations</option>{(data?.organizations??[]).map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</NativeSelect>{period==='CUSTOM'?<><Input label="From" type="date" value={from} onChange={event=>setFrom(event.target.value)}/><Input label="To" type="date" value={to} onChange={event=>setTo(event.target.value)}/></>:null}</div>{refreshing?<span className="ui-help">Updating activity…</span>:null}</Card>
    {error?<p className="task-form-error">Latest refresh failed: {error}</p>:null}
    {workView==='OVERDUE'?<OverdueCard tasks={overdueTasks}/>:<><div className="team-activity-heading"><div><span className="eyebrow">Review queue</span><h2>{workView==='REVIEWED'?'Reviewed team activity':'Unreviewed team activity'}</h2></div><span className="ui-help">{items.length} event{items.length===1?'':'s'}</span></div><Card className="team-activity-feed">{items.length?<ol>{items.map(item=><li key={item.id} className={item.reviewed?'is-reviewed':''}><div className="team-activity-row"><span className="team-activity-icon"><Icon name="activity"/></span><Link href={`/team-activity/${item.id}`} className="team-activity-main"><div className="team-activity-line"><strong>{teamActivityActor(item)}</strong><span>{teamActivityLabels[item.action]??item.action}</span><b>{item.reviewed?'Reviewed':'New'}</b></div><p>{teamActivityDetail(item)}</p><div className="team-activity-meta">{item.organization_name?<span>{item.organization_name}</span>:null}{item.lead_title?<span>· {item.lead_title}</span>:null}<time>{teamActivityDateTime(item.created_at)}</time></div></Link><div className="team-activity-actions"><Button size="sm" variant="outline" loading={updatingId===item.id} onClick={()=>void toggleReviewed(item)}>{item.reviewed?'Mark unreviewed':'Mark reviewed'}</Button><Link href={`/team-activity/${item.id}`} aria-label="Open activity details" className="team-activity-open"><Icon name="chevron"/></Link></div></div></li>)}</ol>:<EmptyState icon="activity" title="No matching team activity" description="Try clearing one or more filters."/>}</Card></>}
  </div>
}

function OverdueCard({tasks}:{tasks:TaskDetail[]}){return <Card className={tasks.length?'team-overdue-card has-risk':'team-overdue-card'}><div className="team-overdue-head"><div><strong>Overdue delivery</strong><div className="ui-help">Tasks past deadline and not yet completed. Open a task to review the responsible staff member and delivery history.</div></div><strong>{tasks.length}</strong></div>{tasks.length?<div>{tasks.slice(0,12).map(task=><Link key={task.id} href={`/tasks/${task.id}`} className="team-overdue-row"><span><strong>{task.title}</strong><small>{[task.assignee_first_name,task.assignee_last_name].filter(Boolean).join(' ')||'Unassigned'} · {task.organization_name||task.lead_title||'General'}</small></span><span>Due {task.due_at?teamActivityDateTime(task.due_at):'—'}</span></Link>)}</div>:<div className="ui-help">No overdue tasks right now.</div>}</Card>}
