'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { PageErrorState, PageLoadingState } from '@/components/ui/page-state';
import { getTeamActivity, updateTeamActivityReview, type TeamActivityItem } from '@/lib/team-activity/api';
import { teamActivityActor, teamActivityDateTime, teamActivityDetail, teamActivityLabels } from './team-activity-view';

function relatedLinks(item: TeamActivityItem) { return [item.lead_id?{label:item.lead_title||'Open Lead',href:`/leads/${item.lead_id}`,kind:'Lead'}:null,item.task_id?{label:item.task_title||'Open Task',href:`/tasks/${item.task_id}`,kind:'Task'}:null].filter(Boolean) as Array<{label:string;href:string;kind:string}>; }
function friendlyValue(value:Record<string,unknown>|null){return !value||!Object.keys(value).length?'No additional event data was recorded.':JSON.stringify(value,null,2)}

export function TeamActivityDetailView({activityId}:{activityId:string}){
  const[item,setItem]=useState<TeamActivityItem|null>(null),[response,setResponse]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  async function refresh(){try{const value=await getTeamActivity(activityId);setItem(value);setResponse(value.review_note??'');return value}catch(caught){setError(caught instanceof Error?caught.message:'Unable to load activity details.');return null}}
  useEffect(()=>{let cancelled=false;getTeamActivity(activityId).then(value=>{if(!cancelled){setItem(value);setResponse(value.review_note??'');setError(null)}}).catch((caught:unknown)=>{if(!cancelled)setError(caught instanceof Error?caught.message:'Unable to load activity details.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[activityId]);
  if(loading&&!item)return <PageLoadingState/>; if(error&&!item)return <PageErrorState message={error}/>; if(!item)return <PageErrorState message="Activity not found."/>;
  const links=relatedLinks(item);
  async function saveReview(input:{reviewed?:boolean;response?:string|null},success:string){setSaving(true);setMessage(null);setError(null);try{await updateTeamActivityReview(activityId,input);setMessage(success);await refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Unable to update activity review.')}finally{setSaving(false)}}
  return <div className="team-activity-detail-page"><div className="team-detail-top"><Link href="/team-activity">← Team Activity</Link><time>{teamActivityDateTime(item.created_at)}</time></div><Card className="team-detail-hero"><div className="team-detail-hero-head"><div><span className="eyebrow">Activity detail</span><h2>{teamActivityLabels[item.action]??item.action}</h2><p>{teamActivityDetail(item)}</p></div><span className={item.reviewed?'team-review-pill is-reviewed':'team-review-pill'}>{item.reviewed?'Reviewed':'Needs review'}</span></div><div className="team-detail-facts">{[['Staff',teamActivityActor(item)],['Type',teamActivityLabels[item.action]??item.action],['Lead',item.lead_title||'—'],['Organization',item.organization_name||'—']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></Card><div className="team-detail-layout"><Card className="team-review-card"><span className="eyebrow">Admin review</span><h3>Review and respond</h3><p className="ui-help">Leave an internal response about this completed activity. Saving a response marks the activity as reviewed.</p><label className="ui-field"><span className="ui-label">Response</span><textarea className="ui-input" value={response} onChange={event=>setResponse(event.target.value)} rows={6} placeholder="Add feedback, follow-up direction, acknowledgement or a review note…"/></label>{message?<p className="team-review-success">{message}</p>:null}{error?<p className="task-form-error">{error}</p>:null}<div className="team-review-actions"><Button loading={saving} onClick={()=>void saveReview({response},'Response saved and activity marked reviewed.')}>Save response</Button><Button variant="outline" loading={saving} onClick={()=>void saveReview({reviewed:!item.reviewed},item.reviewed?'Activity marked unreviewed.':'Activity marked reviewed.')}>{item.reviewed?'Mark unreviewed':'Mark reviewed'}</Button></div></Card><div className="team-detail-side"><Card><div className="ui-card-content"><span className="eyebrow">Related work</span><h3>Open related records</h3>{links.length?<div className="team-related-links">{links.map(link=><Link key={link.href} href={link.href}><span>{link.kind}</span><strong>{link.label}</strong></Link>)}</div>:<p className="muted">No directly related Lead or Task was resolved for this event.</p>}</div></Card><Card><div className="ui-card-content"><details><summary>Event data</summary><p className="ui-help">Audit snapshot captured when the activity occurred.</p><pre className="team-event-pre">{friendlyValue(item.new_values)}</pre></details></div></Card></div></div></div>
}
