import { apiFetch } from '@/lib/api/client';
export type Organization={id:string;name:string;legal_name:string|null;organization_type:'PROSPECT'|'CUSTOMER'|'PARTNER'|'OTHER';industry:string|null;email:string|null;phone:string|null;website:string|null;address_line1:string|null;address_line2:string|null;city:string|null;state:string|null;country:string|null;notes:string|null;assigned_owner_id:string|null;owner_first_name:string|null;owner_last_name:string|null;owner_email:string|null;status:'ACTIVE'|'INACTIVE'|'ARCHIVED';created_at:string;updated_at:string};
export type Organization360={organization:Organization;contacts:Array<Record<string,unknown>&{id:string;first_name:string;last_name:string;job_title:string|null;email:string|null;phone:string|null;is_primary:boolean;method_count:number;verified_method_count:number}>;leads:Array<Record<string,unknown>&{id:string;title:string;record_type:'LEAD'|'PROSPECT'|'CLIENT';stage:string;priority:string;pursuit_progress:number;assigned_to_id:string|null;owner_first_name:string|null;owner_last_name:string|null;created_at:string}>;tasks:Array<Record<string,unknown>&{id:string;title:string;status:string;priority:string;due_at:string|null;assignee_first_name:string|null;assignee_last_name:string|null}>;activities:Array<Record<string,unknown>&{id:string;title:string;activity_type:string;status:string;outcome:string|null;created_at:string;actor_first_name:string|null;actor_last_name:string|null}>;summary:{contacts:number;leads:number;prospects:number;clients:number;openTasks:number;activities:number};currentRecord:Record<string,unknown>|null};
type R<T>={success:boolean;data:T};
export async function listOrganizations():Promise<Organization[]>{return(await apiFetch<R<Organization[]>>('/admin/organizations')).data}
export async function getOrganization360(id:string):Promise<Organization360>{return(await apiFetch<R<Organization360>>(`/admin/organizations/${id}/360`)).data}
export async function createOrganization(input:Record<string,unknown>):Promise<Organization>{return(await apiFetch<R<Organization>>('/admin/organizations',{method:'POST',body:JSON.stringify(input)})).data}
export async function updateOrganization(id:string,input:Record<string,unknown>):Promise<Organization>{return(await apiFetch<R<Organization>>(`/admin/organizations/${id}`,{method:'PATCH',body:JSON.stringify(input)})).data}
export async function setOrganizationStatus(id:string,status:Organization['status']):Promise<Organization>{return(await apiFetch<R<Organization>>(`/admin/organizations/${id}/status`,{method:'POST',body:JSON.stringify({status})})).data}
