import {apiFetch} from '@/lib/api/client';type R<T>={success:boolean;data:T};
export type Notice={id:string;title:string;body:string|null;kind:string;href:string|null;read_at:string|null;created_at:string};
export type DirectContact={id:string;first_name:string;last_name:string;job_title:string|null;unread_count?:number;last_message?:string|null;last_message_at?:string|null};
export type DirectMessage={id:string;sender_user_id:string;body:string;read_at:string|null;delivered_at?:string|null;created_at:string;first_name:string;last_name:string;attachments?:Array<{id:string;file_name:string;mime_type:string;file_size:number}>};
export const listNotifications=async()=> (await apiFetch<R<Notice[]>>('/notifications')).data;
export const readNotice=async(id:string)=> (await apiFetch<R<Notice>>(`/notifications/${id}/read`,{method:'POST'})).data;
export const readAllNotices=async()=>apiFetch<R<boolean>>('/notifications/read-all',{method:'POST'});
export const directContacts=async()=> (await apiFetch<R<DirectContact[]>>('/direct-chat/contacts')).data;
export const directConversation=async(id:string)=> (await apiFetch<R<{conversation:{id:string};messages:DirectMessage[]}>>(`/direct-chat/${id}`)).data;
export const sendDirect=async(id:string,body:string)=> (await apiFetch<R<DirectMessage>>(`/direct-chat/${id}`,{method:'POST',body:JSON.stringify({body})})).data;
export const listManagedDepartments=async()=> (await apiFetch<R<any[]>>('/admin/departments-manage')).data;
export const createManagedDepartment=async(body:any)=> (await apiFetch<R<any>>('/admin/departments-manage',{method:'POST',body:JSON.stringify(body)})).data;
export const patchManagedDepartment=async(id:string,body:any)=> (await apiFetch<R<any>>(`/admin/departments-manage/${id}`,{method:'PATCH',body:JSON.stringify(body)})).data;
export const listManagedTeams=async()=> (await apiFetch<R<any[]>>('/admin/teams-manage')).data;
export const createManagedTeam=async(body:any)=> (await apiFetch<R<any>>('/admin/teams-manage',{method:'POST',body:JSON.stringify(body)})).data;
export const patchManagedTeam=async(id:string,body:any)=> (await apiFetch<R<any>>(`/admin/teams-manage/${id}`,{method:'PATCH',body:JSON.stringify(body)})).data;
export const listReminders=async()=> (await apiFetch<R<any[]>>('/calendar/reminders')).data;
export const createReminder=async(body:any)=> (await apiFetch<R<any>>('/calendar/reminders',{method:'POST',body:JSON.stringify(body)})).data;
export type SearchResult={kind:string;id:string;title:string;subtitle:string;href:string};
export const crmSearch=async(q:string)=> (await apiFetch<R<SearchResult[]>>(`/crm-search?q=${encodeURIComponent(q)}`)).data;
export const uploadDirectAttachment=async(id:string,file:File)=>{const form=new FormData();form.append('file',file);return (await apiFetch<R<DirectMessage>>(`/direct-chat/${id}/attachments`,{method:'POST',body:form})).data};
export const getDirectAttachment=async(id:string)=> (await apiFetch<R<{url:string;fileName:string;mimeType:string}>>(`/direct-chat/attachments/${id}`)).data;
export const listBroadcasts=async()=> (await apiFetch<R<any[]>>('/admin/broadcasts')).data;
export const createBroadcast=async(body:any)=> (await apiFetch<R<any>>('/admin/broadcasts',{method:'POST',body:JSON.stringify(body)})).data;
export const listManagedTeamMembers=async(id:string)=> (await apiFetch<R<any[]>>(`/admin/teams-manage/${id}/members`)).data;
export const updateManagedTeamMembers=async(id:string,body:{memberIds:string[];managerId?:string|null})=> (await apiFetch<R<any[]>>(`/admin/teams-manage/${id}/members`,{method:'PATCH',body:JSON.stringify(body)})).data;
export const staffOpsAnalytics=async()=> (await apiFetch<R<any>>('/admin/staff-ops-analytics')).data;

export type SharedFolderScopes={
  staff:Array<{id:string;first_name:string;last_name:string;email?:string;job_title:string|null;status?:string}>;
  departments:Array<{id:string;name:string;is_active?:boolean}>;
  teams:Array<{id:string;name:string;is_active?:boolean}>;
  roles:Array<{id:string;name:string;code:string;is_active?:boolean}>;
  leads:Array<{id:string;title:string;subtitle:string|null}>;
  tasks:Array<{id:string;title:string;subtitle:string|null}>;
};
export const listSharedFolderScopes=async()=> (await apiFetch<R<SharedFolderScopes>>('/shared-folder-scopes')).data;
export const listSharedFolders=async()=> (await apiFetch<R<any[]>>('/shared-folders')).data;
export const createSharedFolder=async(body:any)=> (await apiFetch<R<any>>('/shared-folders',{method:'POST',body:JSON.stringify(body)})).data;
export const approveSharedFolder=async(id:string,status:'PUBLISHED'|'REJECTED')=> (await apiFetch<R<any>>(`/admin/shared-folders/${id}/approval`,{method:'PATCH',body:JSON.stringify({status})})).data;
export const listSharedFiles=async(id:string)=> (await apiFetch<R<any[]>>(`/shared-folders/${id}/files`)).data;
export const uploadSharedFile=async(id:string,file:File)=>{const form=new FormData();form.append('file',file);return (await apiFetch<R<any>>(`/shared-folders/${id}/files`,{method:'POST',body:form})).data};
export const downloadSharedFile=async(id:string)=> (await apiFetch<R<{url:string;fileName:string}>>(`/shared-files/${id}/download`)).data;

export type SharedAccessGrant={subject_type:'STAFF'|'DEPARTMENT'|'TEAM'|'ROLE';subject_id:string;can_manage:boolean};
export type SharedAccessState={itemType:'FOLDER'|'FILE';id:string;everyone:boolean;publicationStatus:string|null;inheritFolderAccess:boolean|null;grants:SharedAccessGrant[]};
export const getSharedFolderAccess=async(id:string)=> (await apiFetch<R<SharedAccessState>>(`/shared-folders/${id}/access`)).data;
export const setSharedFolderAccess=async(id:string,body:{everyone:boolean;grants:Array<{subjectType:string;subjectId:string;canManage:boolean}>})=> (await apiFetch<R<SharedAccessState>>(`/shared-folders/${id}/access`,{method:'PATCH',body:JSON.stringify(body)})).data;
export const getSharedFileAccess=async(id:string)=> (await apiFetch<R<SharedAccessState>>(`/shared-files/${id}/access`)).data;
export const setSharedFileAccess=async(id:string,body:{inheritFolderAccess:boolean;grants:Array<{subjectType:string;subjectId:string;canManage:boolean}>})=> (await apiFetch<R<SharedAccessState>>(`/shared-files/${id}/access`,{method:'PATCH',body:JSON.stringify(body)})).data;

export const createGoogleCalendarEvent=async(body:any)=> (await apiFetch<R<any>>('/google-calendar/events',{method:'POST',body:JSON.stringify(body)})).data;
