'use client';
import type { ReactNode } from 'react';
import { useCallback,useEffect,useState } from 'react';
import { usePathname } from 'next/navigation';
import { adminNavigation } from '@/components/navigation/admin-navigation';
import { staffNavigation } from '@/components/navigation/staff-navigation';
import { Skeleton } from '@/components/ui/skeleton';
import { getCurrentCrmUser } from '@/lib/auth/current-user';
import { hasAdministrativeAccess,routeForUser } from '@/lib/auth/routing';
import type { CrmUser } from '@/types/auth';
import { AppSidebar } from './app-sidebar';import { AppTopbar } from './app-topbar';import { MobileNavigation } from './mobile-navigation';import { PageContainer } from './page-container';import { PageHeader } from './page-layout';
export function AppShell({area,title,description,personalize,breadcrumb,children}:{area:'admin'|'staff';title:string;description?:string;personalize?:'welcome'|'greeting';breadcrumb?:string;children:ReactNode}){const path=usePathname();const [user,setUser]=useState<CrmUser|null>(null);const [collapsed,setCollapsed]=useState(()=>typeof window!=='undefined'&&localStorage.getItem('planora-sidebar-collapsed')==='true');const [mobileOpen,setMobileOpen]=useState(false);useEffect(()=>{async function authorize(){try{const current=await getCurrentCrmUser();const admin=hasAdministrativeAccess(current);if((area==='admin'&&!admin)||(area==='staff'&&admin)){window.location.replace(routeForUser(current));return}setUser(current)}catch{window.location.replace('/login')}}void authorize()},[area]);const closeMobile=useCallback(()=>setMobileOpen(false),[]);function toggle(){setCollapsed(value=>{const next=!value;localStorage.setItem('planora-sidebar-collapsed',String(next));return next})}if(!user)return <main className="centered-page" aria-busy="true"><div style={{width:320}} className="stack"><Skeleton height={32}/><Skeleton height={120}/></div></main>;const navigation=area==='admin'?adminNavigation:staffNavigation;const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';const personal=personalize==='welcome'?`Welcome back, ${user.first_name}.`:personalize==='greeting'?`${greeting}, ${user.first_name}.`:'';return <div className="app-shell" data-collapsed={collapsed}><div className="desktop-sidebar"><AppSidebar navigation={navigation} path={path} collapsed={collapsed} onToggle={toggle}/></div><MobileNavigation open={mobileOpen} onClose={closeMobile} navigation={navigation} path={path}/><div className="app-main"><AppTopbar user={user} title={title} onOpenNavigation={()=>setMobileOpen(true)}/><main className="app-content"><PageContainer><PageHeader title={title} breadcrumb={breadcrumb} description={`${personal} ${description??''}`.trim()}/>{children}</PageContainer></main></div></div>}
